# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1fea9eb0dfd5ab8d421c2e2345a8fabaaa8a9092e0e856ee7d707043e29cc627672e27478026e7816f2dc8d1cf086c82714101f236df43f5f98558c7a799f3f

test:
  secret_key_base: d83c5091b5bcbae5ca2ddf592b2ee82aea2bfec8ad7d3c511d3e8c77093f1e86a4bd4dcdef3898d0ebd87f8bb165eff65a546f84c86a431803ee0fc0cf931d87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
