# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a461ca0004b122d0a4f0e40215dfc6de02b2739c9cfe8faf27b36685c696c9bdbe7f79745e607562dbe8ec6f499c6f34cc85756a4ed7ce1a2e8ec40fb2178eb

test:
  secret_key_base: 1e3172f5166f95f1087950c017305bc0464a5a008a364d0bace29adf4278ee5e78987edd89b563a0ea59b6a905645c40d483a43c515cbc5cff6b9a5853838522

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
