# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f6f4af50039ad33c6e686af68ad9480c73c4448c6d664f0db9abe88957d95195a2c3ca786aa8670d7040fe552b590373ebe07fa467692bddc9eb3ac46c6e247

test:
  secret_key_base: 4a7c38ccf82cbdf72d9b3ef7da51e4e43f69a6a8305a14f1d047514713aebfb5087927374fa0518b55e8e8888fabe38e90254b57eb910bd18eea38313bbcc0d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
