# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5d93bec0c1a919634af37e1627f47b540c4cc59f2c417aba0dc0481f6e22969261e08e9037eac8d493bf0a2649b7ea9cdd8131e4f7e33616fb5de6d95b1e130

test:
  secret_key_base: 8ab2595b63b513b82ca40625578de08ae0e7948414ed59452edd4ae39fc6f75375b42819abb58726ec89dcc78e1b7c9bf2666bfbdf56eb13122eb411ca1ae20a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
