# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9766163610a12824b54e1d6a8c29b3351d2b8de6de27ac7f2b88689114cfff1a00bcf9eddfbc65fd4db1cc1deb24a4b3afd5d32582861b11bc967a55fe26a668

test:
  secret_key_base: 71a4622f6bc944fd6d4a25a308f4ee8f08a2863542a5236938a177b79aed1e0fbe26ce0f4099cc2a24996420139160d1bb8acab4a79dfcf92c264816bfb9d9da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
